version: "3.8"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
  node:
    build:
      context: ./node-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
